effect:
  name: Set effect
  description: Control the effect settings of WLED.
  target:
  fields:
    effect:
      name: Effect
      description: Name or ID of the WLED light effect.
      example: "Rainbow"
      selector:
        text:
    intensity:
      name: Effect intensity
      description: Intensity of the effect. Number between 0 and 255.
      example: 100
      selector:
        number:
          min: 0
          max: 255
          step: 1
          mode: slider
    palette:
      name: Color palette
      description: Name or ID of the WLED light palette.
      example: "Tiamat"
      selector:
        text:
    speed:
      name: Effect speed
      description: Speed of the effect. Number between 0 (slow) and 255 (fast).
      example: 150
      selector:
        number:
          min: 0
          max: 255
          step: 1
          mode: slider
    reverse:
      name: Reverse effect
      description:
        Reverse the effect. Either true to reverse or false otherwise.
      default: false
      example: false
      selector:
        boolean:

preset:
  name: Set preset
  description: Set a preset for the WLED device.
  target:
  fields:
    preset:
      name: Preset ID
      description: ID of the WLED preset
      example: 6
      selector:
        number:
          min: -1
          max: 65535
          mode: box
